config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
    post 'admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
    delete 'admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
    post 'admin/guest_sign_in' => 'admin/sessions#guest_sign_in', as: 'guest_session'
  end

  namespace :admin do
    resources :companies, only: [:new, :create, :show, :edit, :update, :index]
    resources :contacts, only: [:index, :show]
  end

  scope module: :public do
    root "homes#top"
    get    '/login' => 'sessions#new'
    post   '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    post   '/guest_login' => 'sessions#guest_create'
    patch 'guest_admin_change' => 'employees#guest_admin_change'
    resources :contacts, only: [:create]
    resources :schedules do
      patch 'status' => 'schedules#status'
      resources :schedule_comments, only: [:create, :destroy]
      resource :schedule_favorites, only: [:create, :destroy]
    end
    resources :employees do
      get 'password' => 'employees#password'
      patch 'update_password' => 'employees#update_password'
      get 'calendars' => 'calendars#index'
    end
    resources :questions, only: [:index]
    resources :replies, only: [:index]
    resources :searches, only: [:index]
    resources :how_tos, only: [:index]
    resources :groups do
      get 'employee_list' => 'groups#employee_list'
      resource :group_relationships, only: [:new, :create, :destroy]
    end
  end
end

app/views/shared/_comments_view.html.erb
<% schedule.schedule_comments.each do |comment| %>
  <div id="comment_<%= comment.id %>"class="comment-block">
    <div class="row">
      <div class="col-lg-2 col-md-3 col-sm-4 col-3 text-center">
        <%= link_to employee_path(comment.employee) do %>
          <%= attachment_image_tag comment.employee, :image, width: "70px", height: "70px",
           format: "jpeg", fallback: "no_image.jpeg", class: "schedule-image"%>
        <% end %>
        <% if admin_employee_login? || comment.employee == current_employee %>
          <p>
            <%= link_to "", schedule_schedule_comment_path(comment.schedule, comment), class: "fas fa-trash-alt mb-3",
             remote: true, method: :delete, data: { confirm: '削除しますか？' } %>
          </p>
        <% end %>
      </div>
      <div class="col-md-9 col-sm-8 col-9">
        <p class="schdule-text"><%= comment.created_at.strftime("%y年%m月%d日 %H:%M") %></p>
        <p class="schdule-text mb-2"><%= comment.employee.name %></p>
        <p class="schdule-text"><%= simple_format(h(comment.comment)) %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_error_message.html.erb
<% if object.errors.include?(column) %>
  <span class="error-label"><%= object.errors.full_messages_for(column).first %></span>
<% end %>

app/views/shared/_favorite_button.html.erb
<% if schedule.favorited_by?(current_employee) %>
  <%= link_to schedule_schedule_favorites_path(schedule),
      method: :delete, remote: true, class: "link-z favorite" do %>
    <i class="fas fa-heart icon-color-red mb-3 pr-1"></i>
    <span id="favorite-count-<%= schedule.id %>" class="text-blue mr-1">
      <%= schedule.schedule_favorites.size %>
    </span>
  <% end %>
<% else %>
  <%= link_to schedule_schedule_favorites_path(schedule),
      method: :post, remote: true, class: "link-z favorite" do %>
    <i class="far fa-heart mb-3 pr-1 icon-color-blue favorite"></i>
    <span id="favorite-count-<%= schedule.id %>" class="text-blue mr-1">
      <%= schedule.schedule_favorites.size %>
    </span>
  <% end %>
<% end %>

app/views/shared/_schedule_post.html.erb
<div class="schedule-block">
<%= link_to "", schedule_path(schedule), class: "link", id: "schedule-post-#{schedule.id}" %>
  <div class="row">
    <div class="col-lg-2 col-md-3 col-sm-4 col-3 text-center">
      <%= link_to employee_path(schedule.employee) do %>
        <%= attachment_image_tag schedule.employee, :image, format: "jpeg",
            fallback: "no_image.jpeg", class: "schedule-image link-z"%>
      <% end %>
      <% if admin_employee_login? || schedule.employee == cuurent_employee %>
        <% if schedule.schedule_status == "質問中" %>
          <p>
            <%= link_to "", schedule_status_path(schedule),
                class: "fas fa-question icon-color-red icon-size-15 link-z", method: :patch %>
          </p>
        <% elsif schedule.schedule_status == "解決済質問" %>
          <p>
            <%= link_to "", schedule_status_path(schedule),
                class: "fas fa-lightbulb icon-color-orange icon-size-15 link-z", method: :patch %>
          </p>
        <% end %>
        <p>
          <%= link_to "", edit_schedule_path(schedule), class: "fas fa-edit mb-3 link-z" %>
          <%= link_to "", schedule_path(schedule), class: "fas fa-trash-alt mb-3 link-z",
                          method: :delete, data: { confirm: '削除しますか？' } %>
        </p>
      <% else %>
        <% if schedule.schedule_status == "質問中" %>
          <p>
            <i class="fas fa-question icon-color-red icon-size-15 mb-3"></i>
          </p>
        <% elsif schedule.schedule_status == "解決済質問" %>
          <p>
            <i class="fas fa-lightbulb icon-color-orange icon-size-15 mb-3"></i>
          </p>
        <% end %>
      <% end %>
    </div>

    <div class="col-md-9 col-sm-8 col-9">
      <p class="schdule-text"><%= schedule.start_and_end_time %></p>
      <p class="schdule-text"><%= schedule.employee.name %></p>
      <h4 class="schdule-text mb-2"><%= schedule.title %></h4>
      <p class="schdule-text"><%= simple_format(h(schedule.content)) %></p>
      <% unless schedule.question.blank? %>
        <div class="schedule-question-block-<%= schedule.css_name %> mb-3 p-2">
          <u class="schdule-text"><%= schedule.schedule_status %></u>
          <p class="schdule-text"><%= simple_format(h(schedule.question)) %></p>
        </div>
      <% end %>

      <span id="favorite_<%= schedule.id %>">
        <%= render 'shared/favorite_button', current_employee: current_employee, schedule: schedule %>
      </span>

      <i class="fas fa-comment pr-1 icon-color-blue"></i>
      <span class="text-blue" id="comment_count"><%= schedule.schedule_comments.size %></span>

    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<nav class="col-sm-3">
  <div class="sidebar">
    <ul class="nav flex-column">
      <li class="nav-item"><%= link_to 'ホーム', schedules_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to '使用方法', how_tos_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to 'カレンダー', employee_calendars_path(current_employee), class: "nav-link" %></li>
      <li class="nav-item">
        <%= link_to questions_path, class: "nav-link" do %>
          質問一覧
          <% if @schedule_questions_count >= 1 %>
            <span class="badge badge-pill badge-danger ml-2"><%= @schedule_questions_count %></span>
          <% end %>
        <% end %>
      </li>
      <li class="nav-item">
        <%= link_to replies_path, class: "nav-link" do %>
          返信一覧
          <% if @schedule_replies_count >= 1 %>
            <span class="badge badge-pill badge-danger ml-2"><%= @schedule_replies_count %></span>
          <% end %>
        <% end %>
      </li>
      <li class="nav-item"><%= link_to '検索', searches_path, class: "nav-link" %></li>
      <li class="nav-item"><%= link_to 'グループ一覧', groups_path, class: "nav-link" %></li>
    </ul>
  </div>
</nav>