config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: :all
  devise_scope :admin do
    get 'admin/sign_in' => 'admin/sessions#new', as: 'new_admin_session'
    post 'admin/sign_in' => 'admin/sessions#create', as: 'admin_session'
    delete 'admin/sign_out' => 'admin/sessions#destroy', as: 'destroy_admin_session'
    post 'admin/guest_sign_in' => 'admin/sessions#guest_sign_in', as: 'guest_session'
  end

  namespace :admin do
    resources :companies, only: [:new, :create, :show, :edit, :update, :index]
    resources :contacts, only: [:index, :show]
  end

  scope module: :public do
    root "homes#top"
    get    '/login' => 'sessions#new'
    post   '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    post   '/guest_login' => 'sessions#guest_create'
    patch 'guest_admin_change' => 'employees#guest_admin_change'
    resources :contacts, only: [:create]
    resources :schedules do
      patch 'status' => 'schedules#status'
      resources :schedule_comments, only: [:create, :destroy]
      resource :schedule_favorites, only: [:create, :destroy]
    end
    resources :employees do
      get 'password' => 'employees#password'
      patch 'update_password' => 'employees#update_password'
      get 'calendars' => 'calendars#index'
    end
    resources :questions, only: [:index]
    resources :replies, only: [:index]
    resources :searches, only: [:index]
    resources :how_tos, only: [:index]
    resources :groups do
      get 'employee_list' => 'groups#employee_list'
      resource :group_relationships, only: [:new, :create, :destroy]
    end
  end
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value| %>
  <% key = "danger" if key == "alert" %>
  <% key = "success" if key == "notice" %>
  <p class="alert alert-<%= key %>">
    <%= value %>
  </p>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-dark navbar-expand-sm back-color-sub">
    <div class="container">
      <% if admin_signed_in? %>
        <%= link_to 'ポスケ！', admin_companies_path, class: "navbar-brand" %>
      <% elsif employee_signed_in? %>
        <%= link_to 'ポスケ！', schedules_path, class: "navbar-brand" %>
      <% else %>
        <%= link_to 'ポスケ！', root_path, class: "navbar-brand" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if admin_signed_in? %>
            <li class="nav-item"><%= link_to '企業登録', new_admin_company_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to '企業一覧', admin_companies_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to '問い合わせ一覧', admin_contacts_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'ログアウト', destroy_admin_session_path, class: "nav-link", method: :delete %></li>
          <% elsif employee_signed_in? %>
            <% if admin_employee_login? %>
              <li class="nav-item"><%= link_to '従業員新規登録', new_employee_path, class: "nav-link" %></li>
            <% end %>
            <li class="nav-item"><%= link_to 'スケジュール作成', new_schedule_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'マイページ', employee_path(current_employee), class: "nav-link" %></li>
            <li class="nav-item"><%= link_to 'ログアウト', logout_path, class: "nav-link", method: :delete %></li>
          <% else %>
            <li class="nav-item"><%= link_to '管理ページログイン', new_admin_session_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to '従業員ログイン', login_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ポスケ！</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link href='/fullcalendar/main.css' rel='stylesheet' />
    <script src='/fullcalendar/main.js'></script>
  </head>

  <body id="bodyid" data-controller="<%= controller_name %>" data-action="<%= action_name %>">
    <%= render 'layouts/header' %>
    <div class="container">
      <div id="flash_message">
        <%= render 'layouts/flash_message', flash: flash %>
      </div>
      <%= yield %>
    </div>
    <footer></footer>
  </body>
</html>